I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script
    $ renpy.pause(0, hard=True, delay=0)
  File "game/script.rpy", line 22, in <module>
    $ renpy.pause(0, hard=True, delay=0)
TypeError: pause() got multiple values for argument 'delay'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script
    $ renpy.pause(0, hard=True, delay=0)
  File "C:\Users\student\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\student\Desktop\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 22, in <module>
    $ renpy.pause(0, hard=True, delay=0)
TypeError: pause() got multiple values for argument 'delay'

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
Hunters Academy 1.0
Fri May 17 09:09:43 2024
